const pacientes = new Array(
    {
        id: 1,
        nombre: 'Lucia',
        apellido: 'Alvarez',
        edad: 45,
        diagnostico: 'Gripe',
        numeroSS: 'A234567',
    },
    {
        id: 2,
        nombre: 'Carlos',
        apellido: 'Andres',
        edad: 56,
        diagnostico: 'Conjuntivitis',
        numeroSS: 'K34567000',
    },
    {
        id: 3,
        nombre: 'Jose',
        apellido: 'Dominguez',
        edad: 67,
        diagnostico: 'Coronavirus',
        numeroSS: 'O934571',
    },
    {
        id: 4,
        nombre: 'Elena',
        apellido: 'Prados',
        edad: 18,
        diagnostico: 'Asma',
        numeroSS: 'I823455',
    },
    {
        id: 5,
        nombre: 'Maria',
        apellido: 'Carreño',
        edad: 45,
        diagnostico: 'Cancer',
        numeroSS: 'P123454',
    },
    {
        id: 6,
        nombre: 'Pepe',
        apellido: 'Guzman',
        edad: 89,
        diagnostico: 'Asma',
        numeroSS: 'Q12362548',
    },
    {
        id: 7,
        nombre: 'Ricardo',
        apellido: 'Gomez',
        edad: 24,
        diagnostico: 'Conjuntivitis',
        numeroSS: 'I324610',
    },
    {
        id: 8,
        nombre: 'Sasha',
        apellido: 'Grey',
        edad: 28,
        diagnostico: 'Coronavirus',
        numeroSS: 'Q345126',
    },
    {
        id: 9,
        nombre: 'Marta',
        apellido: 'Carrasco',
        edad: 27,
        diagnostico: 'Gripe',
        numeroSS: 'Q124500',
    },
    {
        id: 10,
        nombre: 'Pepe',
        apellido: 'Gomez',
        edad: 65,
        diagnostico: 'Torcedura',
        numeroSS: 'K123652',
    },
    {
        id: 11,
        nombre: 'Pepita',
        apellido: 'Juarez',
        edad: 48,
        diagnostico: 'Gripe',
        numeroSS: 'S231583',
    },
    {
        id: 12,
        nombre: 'Pablo',
        apellido: 'Motos',
        edad: 55,
        diagnostico: 'Torcedura',
        numeroSS: 'R23456',
    },
)